name: Build Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release
        uses: actions/checkout@v6

      - name: Build plugin ZIP
        run: |
          mkdir duracom-maintenance-worker

          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            ./ duracom-maintenance-worker/

          zip -r \
            "duracom-maintenance-worker-${{ github.event.release.tag_name }}.zip" \
            duracom-maintenance-worker

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: duracom-maintenance-worker-${{ github.event.release.tag_name }}.zip